spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rental-equipment-app
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: reneadonayfranco@gmail.com
    password: T
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: "http://localhost:9090/realms/rental-equipment-app"

application:
  file:
    uploads:
      photos-output-path: ./uploads
  security:
    jwt:
      secret-key: zFeN7VFm3Lq6asqS4MbpH8D7vlfu7gO9cuvZmxkax5aW1J4u4Ko5V6zQGkF1EY6u
      expiration: 86400000

server:
  port: 80

mailing:
  frontend:
    activation-url: http://rentalequipmentapp.org/activate-account
